#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         DCOP-Amarok-Player
version:      0.031
version_from: Player.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
